### ISSUE TITLE
ResolutionCard issue

### ISSUE THREAD

**Issue by excllent123** [codeslake/IFAN#8]
Hi  Lee,
     Thanks  for  your kindly share the code
     I  train your model on my own data, it works well on most case,but on resolutioncard  may introduce artifact,it show on img,can you help me?
   
![img](https://user-images.githubusercontent.com/19669013/164955315-9e50d0d9-9ede-43ed-9a00-694f302b1dff.PNG)

Thanks

**Comment by codeslake** [comment]
Hi,

I am afraid that I can help with this.
If the camera and lens used for creating the dataset are different from the camera and lens used for capturing the resolution card, artifacts may occur.
Even if they are the same, artifacts may still occur, if training patches do not contain similar contents as the resolution card.

One solution that I can think of is to include training images of different resolution cards so that the network can be exposed to similar patterns.

**Comment by excllent123** [comment]
Even if  my dataset contain resolution card  with the same sensor,i still face this issue,  i train the model on  mix precision, and i modify input to raw, just simple modify  input  channel  3 to 1, can you give me  more advice  

Thanks

**Comment by codeslake** [comment]
As I said, even if the dataset and the test images are taken with the same camera and lens, the artifact still can occur.

Try to include images of other resolution cards into the dataset and retrain the network.
I will also try to reduce [sigma value](https://github.com/codeslake/IFAN/blob/main/configs/config_IFAN.py#L33) used for augmenting the dataset with Gaussian noises.

**Comment by excllent123** [comment]
Thanks for you kindly  help, I will try it
